### ISSUE TITLE
Рефактор, гиперион-бамп, проверить компоненты в `@ui`

### ISSUE THREAD

**Issue by kirill-ivanovvv** [torin-asakura/shdvor#148]
### С чем связан запрос на фичу?

Бамб гипериона

### Расскажите как вы это себе видите

- последние актуальные изменения - https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion
- рабочая версия до изменений - https://github.com/torin-asakura/shdvor/commit/7afe491ecb811e06faad07f2cd20a6b75bd671ed
- обновил версии пакетов в `@ui`
- верстку компонентов закрыл заглушками, чтобы заниматься Box'ами на уровне fragments & pages
- подключил тему в fragments/root-layout
- добавил response-box. респонс-компоненты нужно переопределять по аналогии.

- [x] - проверить, какие компоненты используются в проекте. часть сверстанны вручную, при том, что есть аналоги в hyperion. лучше их заменить на библиотечные
  - [x] - accordion - rewrite
  - [x] - button
  - [x] - card - rewrite, use hyperion variant if posiible
  - [x] - carousel - rewrite, use hyperion variant if possible
  - [x] - checkbox - rewrite, use hyperion variant if possible
  - [x] - condition - rewrite, use hyperion variant if possible
  - [x] - divider - rewrite
  - [x] - drawer - rewrite
  - [x] - image - rewrite, use hyperion variant if possible
  - [x] - input - rewrite, use hyperion variant if possible
  - [x] - layer - check usage
  - [x] - layout - rewrited
  - [x] - link - rewrite
  - [x] - logo - rewrite
  - [x] - map - check usage
  - [x] - progress - rewrite, use hyperion variant if possible
  - [x] - radio - rewrite
  - [x] - select - rewrite, use hyperion variant if possible
  - [x] - slider - rewrite
  - [x] - social-links - rewrite
  - [x] - switch - rewrite, use hyperion variant if possible
  - [x] - text, just reexport, check usage on page markup
  - [x] - tooltip - reexport, check usage
  - [x] - utils - can change to hyperion version, use-hover etc
  - [x] - wheel - rewrite

**Comment by aliceinapple** [comment]
#### Что сделано:
- рефактор компонентов `divider`, `condition`, `image`, `link`, `tooltip`
#### Что дальше:
продолжить рефактор

**Comment by aliceinapple** [comment]
#### Что сделано:
- рефактор компонентов `logo`, `card`,  `text`
- проверила использование компонента `map`
#### Что дальше:
продолжить рефактор

**Comment by aliceinapple** [comment]
#### Что сделано:
- рефактор компонентов `checkbox`, `progress-bar`
- начала рефактор `select` и `radio`
#### Что дальше:
продолжить рефактор

**Comment by kirill-ivanovvv** [comment]
> * button

@aliceinapple взял button

**Comment by kirill-ivanovvv** [comment]
#### Текущий статус
- рефактор navigation-fragment
- перебирал button. за основу беру компонент из гипериона, копирую код, оставляю минимальное необходимое
#### Дальнейшие планы
- почемуто не видит глобальлные css-переменные, при том, что в `:root` они падают. разбираюсь
![image](https://github.com/user-attachments/assets/cbfc0afb-12da-4039-9783-38a9ab75459d)
![image](https://github.com/user-attachments/assets/cf783aa4-58fd-4a46-a8c5-2fd9ed906b92)
#### Актуальная ветка
- https://github.com/torin-asakura/shdvor/tree/feat/button

**Comment by aliceinapple** [comment]
#### Что сделано:
- рефактор компонентов `select` и `radio`
- исправила стили для `checkbox`
#### Что дальше:
- проверить `select` и `link`
- продолжить рефактор

**Comment by aliceinapple** [comment]
#### Что сделано:
- переписала компоненты `link` и `text`
- исправила стили и форматирование для ранее написанных компонентов
#### Что дальше:
- продолжить рефактор

**Comment by kirill-ivanovvv** [comment]
@aliceinapple Вик, ты занималась `wheel`? я возьму?

**Comment by aliceinapple** [comment]
> @aliceinapple Вик, ты занималась `wheel`? я возьму?

Не занималась, бери

**Comment by aliceinapple** [comment]
@kirill-ivanovvv создавала ветку от твоей https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion, пул реквест делаю в нее, недавно вмержились изменения по рефактору ui, подтяни себе изменения, если работаешь в этой ветке

**Comment by kirill-ivanovvv** [comment]
@aliceinapple `SocialLinks` не занималась?

**Comment by aliceinapple** [comment]
> @aliceinapple `SocialLinks` не занималась?

Нет, можешь брать

**Comment by aliceinapple** [comment]
@kirill-ivanovvv пока занимаюсь `slider`

**Comment by kirill-ivanovvv** [comment]
@aliceinapple :  
- [ ] - slider - rewrite
- [ ] - accordion - rewrite

### todo:
  - [ ] - carousel - rewrite, use hyperion variant if possible
  - [ ] - drawer - rewrite
  - [ ] - input - rewrite, use hyperion variant if possible
  - [ ] - layer - check usage
  - [ ] - switch - rewrite, use hyperion variant if possible
  - [ ] - utils - can change to hyperion version, use-hover etc

@kirill-ivanovvv :
  - [ ] - social-links - rewrite

---

> @kirill-ivanovvv сейчас доделываю `slider`, после него возьму `accordion`

список оставшихся. давай ты сверху цепляй компоненты, я снизу буду? 
так не перечемся

**Comment by aliceinapple** [comment]
> список оставшихся. давай ты сверху цепляй компоненты, я снизу буду из группы `TODO`? так не перечемся

@kirill-ivanovvv хорошо

**Comment by kirill-ivanovvv** [comment]
у `usePopover` из `hyperion` обнаружил баг. при снятии хавера, layer не исчезает.

![image](https://github.com/user-attachments/assets/4b273f8e-d0bc-431d-832c-f1d1994871ad)

- локально у себя пофиксил. [в этом моменте](https://github.com/atls/hyperion/blob/ea10d8cba60353bbb36abba8a44f8b62ab2460ac/utils/use-popover/src/use-popover.hook.ts#L39) нужно назначить стейт `false`

@Nelfimov могу сам создать ПР или передать это Диме?

**Comment by Nelfimov** [comment]
> @Nelfimov могу сам создать ПР или передать это Диме?

Даже нужно самому

**Comment by aliceinapple** [comment]
#### Что сделано:
- переписала компоненты `slider` и `accordion`
#### Что дальше:
- продолжить рефактор

**Comment by kirill-ivanovvv** [comment]
#### Что сделано:
- social-links utils switch

#### Что дальше:
- посмотрететь применение layer на уровне фрагментов. менял пропсы

#### Актуальная ветка:
- https://github.com/torin-asakura/shdvor/tree/feat/layer

**Comment by kirill-ivanovvv** [comment]
> * [ ]  - input - rewrite, use hyperion variant if possible
> *

@aliceinapple не занималась?

**Comment by aliceinapple** [comment]
> > * [ ]   - input - rewrite, use hyperion variant if possible
> 
> @aliceinapple не занималась?

Нет, бери, если все сделал

**Comment by kirill-ivanovvv** [comment]
@aliceinapple обновил https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion

**Comment by kirill-ivanovvv** [comment]
@aliceinapple Вик, ты [здесь](https://github.com/torin-asakura/shdvor/issues/148#issuecomment-2556560091) вроде бы все отметила. Могу взять еще компоненты

**Comment by aliceinapple** [comment]
> @aliceinapple Вик, ты [здесь](https://github.com/torin-asakura/shdvor/issues/148#issuecomment-2556560091) вроде бы все отметила. Могу взять еще компоненты

Эти сделала, нужно будет только проверить, вижу ты уже [таску](https://github.com/torin-asakura/shdvor/issues/163) создал, завтра сделаю пр с последними компонентами и займусь проверкой.

**Comment by aliceinapple** [comment]
#### Что сделано:
- рефактор компонентов `carousel` и `drawer`
#### Что дальше:
- проверить
- запросить ревью

**Comment by kirill-ivanovvv** [comment]
#### Что сделано:
- `layer`
- `input`

#### Что дальше:
- переключился на фрагменты - https://github.com/torin-asakura/shdvor/issues/163

#### Актуальная ветка:
- https://github.com/torin-asakura/shdvor/tree/feat/bump-hyperion
